import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="bg-gray-50">
          <div className="max-w-4xl w-full px-4 mx-auto flex-1">{children}</div>
          <footer className="bg-gray-100 p-4 pt-10 w-full mt-10">
            <div className="max-w-4xl px-4 mx-auto text-xs">
              <p>중부대학교 정보보호학전공 한서진</p>
              <p>seozz2@jmail.ac.kr</p>
              <Link
                href="https://github.com/seojin23"
                className="hover:underline"
              >
                github.com/seojin23
              </Link>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
